name: Test workflow

on:
  push:
    branches:
      - rolling
      - main
  pull_request:
    branches:
      - rolling
      - main

jobs:
  test:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
